dist: focal
language: java
jdk: openjdk11
sudo: enabled 

branches:
  only:
    - master

install: mvn install  -Dgpg.skip
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications: 
 email:
  recipients: 
   - pawel.trajdos@pwr.edu.pl
  on_success: always
  on_failure: always
        
     
