dist: trusty
language: java
jdk: oraclejdk8
sudo: enabled 
before_install:
        - mkdir -p ${HOME}/.ant/lib
        - cd ${HOME}/.ant/lib
        - wget http://ftp.ps.pl/pub/apache//ant/ivy/2.5.0-rc1/apache-ivy-2.5.0-rc1-bin.tar.gz
        - tar -xvf ./*.tar.gz
        - find ./ -type f -name "ivy*\.jar" -exec cp {} ./ \;
        - cd -
install: ant -f ./build_package.xml resolve
script: 
    - ant -f ./build_package.xml exejar
    - ant -f ./build_package.xml run_tests
notifications: 
 email:
  recipients: 
   - pawel.trajdos@pwr.edu.pl
  on_success: always
  on_failure: always
        
     
