dist: trusty
language: java
jdk: oraclejdk8
sudo: enabled 

install: mvn install  -Dgpg.skip
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications: 
 email:
  recipients: 
   - pawel.trajdos@pwr.edu.pl
  on_success: always
  on_failure: always
        
     
