dist: trusty
language: java
jdk: oraclejdk8
sudo: enabled 

script: 
    - mvn clean package

notifications: 
 email:
  recipients: 
   - pawel.trajdos@pwr.edu.pl
  on_success: always
  on_failure: always
        
     
